#Use root/example as user/password credentials
version: '3.1'
   
volumes:
    sonarqube-conf:
    
    sonarqube-data:

    sonarqube-logs:

    sonarqube-extensions:
    
    pgdata:
    
    pgadmin-data:
    
services:
  postgres:
    image: postgres
    container_name: postgres-sonarqube
    restart: always
    environment:
      POSTGRES_DB: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: exemple@test.com
      PGADMIN_DEFAULT_PASSWORD: exemple
      PGADMIN_ENABLE_TLS: 1
    ports:
      - 5443:443
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - /etc/ssl/certs/selfsigned.crt:/certs/server.cert
      - /etc/ssl/private/selfsigned.key:/certs/server.key
      - /tmp/servers.json:/servers.json
  
  sonarqube:
    image: sonarqube
    container_name:: sonarqube
    ports: 
      - 9000:9000
    restart: always
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres-sonarqube/sonar
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
