
# Use postgres/example user/password credentials
version: '3.1'

volumes:
  pgadmin:
  
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 5080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - /tmp/servers.json:/servers.json
