version: '3.1'

volumes:
  grafana-volume:

  influxdb-volume:

services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
      
  influxdb:
    image: influxdb
    environment:
      INFLUXDB_GRAPHITE_ENABLED: true
      INFLUXDB_DB: telegraf
      INFLUXDB_ADMIN_ENABLED: true
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword
      INFLUXDB_USER: telegraf 
      INFLUXDB_USER_PASSWORD: secretpassword
    restart: always
    ports:
      - 8086:8086
      - 2003:2003
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb

networks:
  monitoring:
