version: '3.1'

volumes:
  grafana-volume:

  influxdb-volume:

services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana

networks:
  monitoring:
