version: '3.1'

volumes:
  grafana-volume:

  influxdb-volume:

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=1
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=1
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=telegraf 
      - INFLUXDB_USER_PASSWORD=secretpassword
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
      
  kapacitor:
    image: kapacitor
    depends_on: 
      - influxdb
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_HOSTNAME=kapacitor
      
  cronograf:
    image: chronograf
    entrypoint: 'chronograf --kapacitor-url=http://kapacitor:9092 --influxdb-url=http://influxdb:8086'
    ports:
      - 8888:8888
    networks:
      - monitoring
    depends_on:
      - influxdb
      - kapacitor
      
  telegraf:
    image: telegraf
    networks:
      - monitoring
    volumes:
      - /srv/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

networks:
  monitoring:
